### ISSUE TITLE
Issue With Hover On About & Blogs

### ISSUE THREAD

**Issue by SerotoninShane** [Naresh-Khatri/Portfolio#1]
## Error Image

![error](https://github.com/user-attachments/assets/c8a78892-85c5-4666-9f95-59dd8513616b)

Placeholder text shows up instead of image.

Saw your work on discord, fantastic work! (I tried to to stress-test-it, but it is well built)

**Comment by Naresh-Khatri** [comment]
Congrats on opening the first issue on this repo :100: :confetti_ball: 

Youre right! There are some missing link previews in the nav, it's still a WIP. I'll be working on the about and blog sections asap.

Thanks for the appreciation! It really motivates me. Can I ask you how to tested it? I'd love to use your method for optimize  the perf even further.

**Comment by SerotoninShane** [comment]
Just read through your code and stress tested. Nothing that in depth.

**Comment by Naresh-Khatri** [comment]
heyyy :shushing_face: :shushing_face: :shushing_face: 

you were supposed to keep this a secret lol

**Comment by SerotoninShane** [comment]
I guess they'll have to find out for themselves 🤫
